### ISSUE TITLE
代码在unityEditor 和win发布版都没有问题 但是Android有问题

### ISSUE THREAD

**Issue by leeeasy** [NewbieGameCoder/IllegalWordsDetection#1]
代码在编辑器和 win发布版都可以使用可是发布到Android真机时失效了。什么的都判断不出来，我的关键词数据是加载好的~ 希望作者可以跟进一下 谢谢

**Comment by NewbieGameCoder** [comment]
有没有报错信息什么的哈？IllegalWordDetection.Init传进来的string[]是有效的哈？我用了2个项目，暂时还木有发现问题

**Comment by leeeasy** [comment]
string[] 是正确的log看过了，也没报错就是屏蔽字不起作用判断不到一样。 在编辑器和Win发布版就没问题。和Utf—8什么的有关么？

**Comment by NewbieGameCoder** [comment]
可能是，你保存成utf-8无bom的MinGanCi.txt瞅瞅

**Comment by NewbieGameCoder** [comment]
英文能不能过滤？

**Comment by NewbieGameCoder** [comment]
方便的话，提供个能复现的小工程哇
